name: Google News Scraper

on:
  workflow_dispatch:  # manual trigger only

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium beautifulsoup4 lxml

      - name: Run scraper every 5 minutes for 1 hour
        env:
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          for i in {1..12}; do
            echo "Run #$i at $(date)"
            python scrapping.py
            sleep 60  # wait 5 minutes
          done
